# Generated by Django 5.0.14 on 2026-09-10 06:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('local', 'Local')], max_length=20)),
                ('model_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Non-secret provider configuration only.')),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=150)),
                ('operation', models.CharField(help_text='generate | chat | embed | classify | summarize', max_length=50)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout'), ('RATE_LIMITED', 'Rate limited')], max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='aiproviderconfig',
            constraint=models.UniqueConstraint(fields=('provider', 'model_name'), name='unique_provider_model'),
        ),
        migrations.AddField(
            model_name='aiusagerecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='aiusagerecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiusagerecord',
            index=models.Index(fields=['organization', '-created_at'], name='ai_platform_organiz_ae55aa_idx'),
        ),
    ]
