# Generated by Django 5.0.14 on 2026-09-10 06:37

import apps.file_storage.storages
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='SUDHIXAI', max_length=100)),
                ('legal_name', models.CharField(default='SUDHIXAI TECHNOLOGY PRIVATE LIMITED', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, storage=apps.file_storage.storages.PublicFileSystemStorage(), upload_to='company/')),
                ('favicon', models.ImageField(blank=True, null=True, storage=apps.file_storage.storages.PublicFileSystemStorage(), upload_to='company/')),
                ('seo_default_title', models.CharField(blank=True, max_length=255)),
                ('seo_default_description', models.CharField(blank=True, max_length=500)),
                ('seo_default_og_image', models.ImageField(blank=True, null=True, storage=apps.file_storage.storages.PublicFileSystemStorage(), upload_to='company/seo/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
