# Generated by Django 5.0.14 on 2026-09-10 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.CharField(blank=True, help_text='Short summary shown in grids/cards.', max_length=300)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('hero_description', models.TextField(blank=True)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('use_cases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['sort_order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
