# Generated by Django 5.0.14 on 2026-09-10 06:37

import apps.file_storage.storages
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('COMING_SOON', 'Coming Soon'), ('PRIVATE_PREVIEW', 'Private Preview'), ('BETA', 'Beta'), ('AVAILABLE', 'Available'), ('ARCHIVED', 'Archived')], default='COMING_SOON', max_length=20)),
                ('build_tag', models.CharField(blank=True, max_length=64)),
                ('hero_content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, storage=apps.file_storage.storages.PublicFileSystemStorage(), upload_to='products/')),
                ('website_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('cta_label', models.CharField(blank=True, default='Learn more', max_length=100)),
                ('is_public', models.BooleanField(default=False, help_text='Must be explicitly enabled by an admin before the product appears publicly.')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
